name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name: [
          windows-vs2019-Win32-shared
        ]
        include:

          - name: windows-vs2019-Win32-shared
            os: windows-latest
            triplet: 'x86-windows-static'
            build-system: cmake
            cmake-generator: 'Visual Studio 16 2019'
            cmake-options: >-
              -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>
              -DCMAKE_GENERATOR_PLATFORM=Win32
              -DBUILD_SHARED_LIBS=ON
              -DBUILD_REGTEST=OFF
              -DBUILD_EXAMPLES=OFF
              -DINSTALL_PKGCONFIG_MODULE=OFF
              -DCPACK_PACKAGE_NAME=libsndfile
              -DCMAKE_BUILD_TYPE=Release
              -DVCPKG_TARGET_TRIPLET=x86-windows-static
              -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Windows dependencies
        if: startsWith(matrix.os,'windows')
        run: |
          vcpkg install libvorbis libflac opus sqlite3 speex mp3lame mpg123 --triplet ${{matrix.triplet}}

      - name: Configure, build and test with CMake
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        if: startsWith(matrix.build-system,'cmake')
        run: |
          mkdir build
          cd build
          cmake .. -G "${{matrix.cmake-generator}}" ${{matrix.cmake-options}}
          cmake --build . --config Release
          ctest
          
      - name: Publish build artifact
        run: echo Uploading...
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact-${{ matrix.name }}.zip
          path: build/Release/

